version: "3"

services:
  site:
    build: ./
    networks:
      - localhost
    environment:
      - VIRTUAL_HOST=site.local
      - VIRTUAL_PORT=80
    volumes:
      - ./src:/app:z


networks:
  localhost:
    external: true
